name: CI - Inventory (PR)

on:
  pull_request:
    branches:
      - main
    paths:
      - gc-industries-devops-superheros/superhero-app-code/inventory/**
      - gc-industries-devops-superheros/helm/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          docker build -t inventory:$SHORT_SHA gc-industries-devops-superheros/superhero-app-code/inventory

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: inventory:${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true # Ignore vulnerabilities that do not have a fix available
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'