name: Helm Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'gc-industries-devops-superheros/helm/**'

jobs:
  helm-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Helm lint
        run: |
          helm lint gc-industries-devops-superheros/helm/superheros

      - name: Helm template validation
        run: |
          helm template superheros \
            gc-industries-devops-superheros/helm/superheros > rendered.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v7
        with:
          name: rendered-manifests
          path: rendered.yaml